spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/cathe?useUnicode=true&characterEncoding=utf-8&serverTimezone=CTT
     username: root
     password: 123456
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: false
      database-platform: org.hibernate.dialect.MySQL5Dialect
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
logging:
  level:
    root: info
    com.myblog.blog: debug
  file: log/blog-dev.log
multipart:
  maxFileSize: 50mb
  maxRequestSize: 50Mb

